feat: add fabric support
Cubxity/UnifiedMetrics pull request #33
Opened 2021-07-26 00:04 UTC by DJtheRedstoner

Should be fully functional, however building production jars does not work (the other modules are not shaded correctly). I am currently trying to resolve this issue but please let me know if you have ideas or have found a solution.

2021-07-26 03:15 UTC, Cubxity requested changes

2021-07-26 03:15 UTC, Cubxity commented on fabric/src/main/kotlin/dev/cubxity/plugins/metrics/fabric/bootstrap/UnifiedMetricsFabricBootstrap.kt
> +    override val logger = Log4jLogger(LogManager.getLogger("Unified Metrics"))
Please use "UnifiedMetrics"

2021-07-26 03:15 UTC, Cubxity commented on fabric/src/main/kotlin/dev/cubxity/plugins/metrics/fabric/metrics/events/EventsCollection.kt
> +    private val joinCounter = Counter("minecraft_events_join_total")
You should specify a backing store for non-async events for improve performance

2021-07-26 03:15 UTC, Cubxity commented on fabric/src/main/kotlin/dev/cubxity/plugins/metrics/fabric/metrics/tick/TickCollection.kt
> +    private val tickDuration = Histogram(
Also specify a backing store here

2021-10-02 17:23 UTC, Cubxity commented on platforms/fabric/src/main/kotlin/dev/cubxity/plugins/metrics/fabric/events/ChatEvent.kt
> +        val EVENT: Event<ChatEvent> = EventFactory.createArrayBacked(ChatEvent::class.java) { events ->
Perhaps make this lower-cased, so it translates to `getEvent()` in Java?

2021-10-02 17:25 UTC, Cubxity requested changes

2021-10-02 17:25 UTC, Cubxity commented on platforms/fabric/src/main/kotlin/dev/cubxity/plugins/metrics/fabric/events/PingEvent.kt
> +        val EVENT: Event<PingEvent> = EventFactory.createArrayBacked(PingEvent::class.java) { events ->
Perhaps make this lower-cased, so it translates to `getEvent()` in Java?

2021-10-02 17:25 UTC, Cubxity commented on platforms/fabric/src/main/kotlin/dev/cubxity/plugins/metrics/fabric/events/TickEvent.kt
> +        val EVENT: Event<TickEvent> = EventFactory.createArrayBacked(TickEvent::class.java) { events ->
Perhaps make this lower-cased, so it translates to `getEvent()` in Java?

2021-10-02 17:25 UTC, Cubxity commented on platforms/fabric/src/main/kotlin/dev/cubxity/plugins/metrics/fabric/metrics/events/EventsCollection.kt
> +    private val joinCounter = Counter(Metrics.Events.Join)
These should also use `VolatileDoubleStore`, assuming the event is fired synchronously.

2021-10-02 17:25 UTC, Cubxity commented on platforms/fabric/src/main/kotlin/dev/cubxity/plugins/metrics/fabric/metrics/tick/TickCollection.kt
> +        "minecraft_tick_duration_seconds",
Shouldn't this use the metric name constant?

2021-10-02 17:26 UTC, DJtheRedstoner commented on platforms/fabric/src/main/kotlin/dev/cubxity/plugins/metrics/fabric/metrics/events/EventsCollection.kt
> +    private val joinCounter = Counter(Metrics.Events.Join)
those events are fired on network threads, and not synchronously.

2021-10-02 18:53 UTC, Cubxity approved these changes

2021-10-02 18:54 UTC, merged